intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
import intf_libs += libcrails%lib{crails}

lib{crails-http-client}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_HTTP_CLIENT_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_HTTP_CLIENT_SHARED_BUILD

# Export options.
#
lib{crails-http-client}:
{
  cxx.export.poptions = "-I$out_root/libcrails-http-client" "-I$src_root/libcrails-http-client"
  cxx.export.libs = $intf_libs
}

liba{crails-http-client}: cxx.export.poptions += -DLIBCRAILS_HTTP_CLIENT_STATIC
libs{crails-http-client}: cxx.export.poptions += -DLIBCRAILS_HTTP_CLIENT_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{crails-http-client}: bin.lib.version = "-$version.project_id"
else
  lib{crails-http-client}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libcrails-http-client/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
